#!/bin/bash
#SBATCH --job-name=qmc
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --mem=16G
#SBATCH --partition=desa
#SBATCH --nodelist=desa-compute-01
#SBATCH --gres=gpu:1
#SBATCH -t 72:00:00                     # Time limit (hh:mm:ss)
#SBATCH -o qmc_%j.out                  # Name of stdout output log file (%j expands to jobID)
#SBATCH -e qmc_%j.err                  # Name of stderr output log file (%j expands to jobID)

bash commands/lg_mnist.sh